### ISSUE TITLE
YAY!! FIRST ISSUE!!

### ISSUE THREAD

**Issue by starterdragon** [thebigsmileXD/BossAnnouncement#1]
"Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'BossAnnouncement v1.0.0': Call to undefined method xenialdan\BossBarAPI\API::playerMove() on xenialdan\BossAnnouncement\Main

playerMove() event on BossBarAPI, want me to create an issue there aswell?

**Comment by inxomnyaa** [comment]
Are you sure you have the latest bossbarapi'? i'll check if i updated the code.

**Comment by SerezhaIvanov** [comment]
Make please changing message only in headBar and if player is not near the boss bar work.

**Comment by inxomnyaa** [comment]
@starterdragon that move bug should be fixed, works perfectly for me. 

@SergeyIvanov14 then set 'headmessage' to ''
and only-spawn?

**Comment by VCraftMCPE** [comment]
Not work for me too

**Comment by VCraftMCPE** [comment]
Can I know what softwaire u use

**Comment by inxomnyaa** [comment]
Its software independ. Tested on pmmp, clearsky and genisys.

**Comment by CyanKelv** [comment]
@thebigsmileXD on
https://github.com/thebigsmileXD/BossAnnouncement/blob/master/src/xenialdan/BossAnnouncement/Main.php#L55-L58

API::playerMove() is missing second parameter/argument. it should be $pk = API::playerMove($event->getPlayer(), $this->eid);

**Comment by inxomnyaa** [comment]
why the fuck.. i fixed this already, why is it back..
