### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SerezhaIvanov** [thebigsmileXD/BossAnnouncement#11]
[Tesseract] [20:35:25] CRITICAL> "Невозможно обработать событие 'pocketmine\event\player\PlayerJoinEvent' в 'BossAnnouncement v1.1.2
: Call to undefined method xenialdan\BossBarAPI\BossEventPacket::putEntityId() в xenialdan\BossAnnouncement\Main"
[Tesseract] [20:35:25] CRITICAL> Error: "Call to undefined method xenialdan\BossBarAPI\BossEventPacket::putEntityId()" (EXCEPTION) i
 "/plugins/BossBarAPI/src/xenialdan/BossBarAPI/BossEventPacket" at line 17

**Comment by inxomnyaa** [comment]
Tesseract fault.
