### ISSUE TITLE
BossBar error

### ISSUE THREAD

**Issue by Saxavlax001** [thebigsmileXD/BossAnnouncement#13]
When I'm joining my server,boss bar says loading.,stucks and then disappears sometimes.This started to happen when I changed to pmmp,and I have the 2 bossbar plugins updated.

**Comment by inxomnyaa** [comment]
The latest version _should_ work, but this sounds like an "xx tick" issue. May you recheck the console? K thx,

**Comment by Saxavlax001** [comment]
The server is on a host and I can't see what's happening completely(its rcon console I think)and I had downloaded the latest version,I will try again,but I don't think it will work

**Comment by poustmal** [comment]
The same problem again,and my phone I think is 32 bit or php idk

**Comment by Saxavlax001** [comment]
ok I had outdated bossbarapi version,fixed
