### ISSUE TITLE
Incorrect BossBarAPI Version Dependency

### ISSUE THREAD

**Issue by 95CivicSi** [thebigsmileXD/BossAnnouncement#20]
https://crash.pmmp.io/view/2395433

This crash was caused due to an incorrect dependency in `.poggit.yml`
https://github.com/thebigsmileXD/BossAnnouncement/blob/master/.poggit.yml#L7

The correct version dependency should be 5.0.1.

**Comment by inxomnyaa** [comment]
See PR - BossBarAPI will be deleted soon.
