### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/BossAnnouncement#28]
Hello my server is showing me errors from the plugins can you help me please

Here are the errors:
![BossBar Bug](https://user-images.githubusercontent.com/64487208/88582182-97248180-d04e-11ea-90e4-66402025741b.PNG)

**Comment by inxomnyaa** [comment]
This was fixed in a recent version. Grab the latest dev phar https://poggit.pmmp.io/ci/thebigsmileXD/BossAnnouncement/~
