### ISSUE TITLE
Still 15 bytes unread

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/BossAnnouncement#9]
Warning: assert(): Still 15 bytes unread in xenialdan\BossBarAPI\BossEventPacket failed in /storage/sdcard0/Genisys/src/pocketmine/network/Network.php on line 256

I don't know why this always happen

**Comment by inxomnyaa** [comment]
Old AF. "1 byte" also appears.
Just turn off debug

**Comment by ghost** [comment]
I did turned it off

**Comment by inxomnyaa** [comment]
Thats weird.

**Comment by inxomnyaa** [comment]
Closing due to new PMMP packet solving
